NAME: "exp1713-h264"
DATASETS: [
    # "MOT17-02",
    # "MOT17-04",
    # # "MOT17-05",
    # "MOT17-09",
    # "MOT17-10",
    # "MOT17-11",
    "MOT17-13",
    # "MOT20-02"
  ]
EPOCH: 2
LR: 0.001
MIN_LR: 0.000001
BATCH_SIZE: 12
TRAIN_RATIO: 0.7
REWARD_MAPPING: [1, 1.3, 1.6, 1.9, 2.2]
WEIGHT_MAP: [10]
RESIZE_FACTOR: 4
THRESHOLD_INSIDE: 0.991
THRESHOLD_OUTSIDE: 0.952
EXPLORE_PROB: 0.8
EXPLORE_DECAY: 0.1
